import type {Metadata} from 'next';
import '../globals.css';

export const metadata: Metadata = {
    title: 'Notes | Auth',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    //TODO:add some fonts here, change metadata
    return (
        <html lang='en'>
            <head>
            </head>
            <body className='h-screen w-screen p-0 m-0 overflow-clip'>
                {children}
            </body>
        </html>
    );
}
