import type {Metadata} from 'next';
import '../globals.css';

export const metadata: Metadata = {
    title: 'Notes | Auth',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <head>
                <link
                    rel='preconnect'
                    href='https://fonts.googleapis.com'
                />
                <link
                    rel='preconnect'
                    href='https://fonts.gstatic.com'
                />
                <link
                    href='https://fonts.googleapis.com/css2?family=Akronim&family=Alkatra:wght@400..700&family=Courgette&family=Doto:wght@100..900&family=Inria+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Kite+One&family=Miltonian&display=swap'
                    rel='stylesheet'
                />
            </head>
            <body className='h-screen w-screen p-0 m-0 overflow-clip'>
                {children}
            </body>
        </html>
    );
}
