import '../globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import {
    Quicksand,
    Akronim,
    Courgette,
    Dongle,
    Doto,
    Ephesis,
    Kite_One,
    Love_Light,
    Montez,
    Ms_Madi,
    NTR,
    Offside,
    Oregano,
} from 'next/font/google';
import {ThemeProviders} from '../providers';
import I18nProvider from '@/components/I18nProvider';
import {Suspense} from 'react';
import Loading from '@/components/Loading';
import GlobalSettingsProvider from '@/components/GlobalSettingsProvider';

const quicksand = Quicksand({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
    variable: '--font-quicksand',
});

const akronim = Akronim({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-akronim',
});
const courgette = Courgette({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-courgette',
});
const dongle = Dongle({
    subsets: ['latin'],
    weight: ['300', '400', '700'],
    variable: '--font-dongle',
});
const doto = Doto({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-doto',
});
const ephesis = Ephesis({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-ephesis',
});
const kite_one = Kite_One({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-kite-one',
});
const love_light = Love_Light({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-love-light',
});
const montez = Montez({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-montez',
});
const ms_madi = Ms_Madi({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-ms-madi',
});
const ntr = NTR({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-ntr',
});
const offside = Offside({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-offside',
});
const oregano = Oregano({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-oregano',
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
